# Abstract

There has always been a significant overlap between queer communities and kink communities, both historically [@Gay-BDSM-History; @Lesbian-Sadomasochism] and in the present day [@LGBTQ+Kink], and this overlap often manifests in sociopolitical alignments. Leathermen's clubs funded and fundraised for pride marches and protests, Leathermen and Leatherdykes were instrumental in addressing the AIDS crisis, LGBT+ groups have advocated against the shuttering of kink-friendly venues, and individuals situated in the overlap are frequent and visible presences in politics and media [@Leather-and-AIDS-Crisis].

The modern political landscape across much of the anglosphere, particularly in the UK, is virulently and increasingly transphobic [@Afraid-of-Gender] and misogynistic [@Misogyny-Nottingham]. A majority of the Queer* community self-report pro-trans beliefs, and attitudes towards women are generally more egalitarian, though patterns of discrimination are still prevelant.

We look to explore a straightforward but deep question: in what ways do gender and gender identity influence the experiences of kinksters participating in the petplay scene?

This pre-registration lays out the questions we plan to study, the methodology and analysis we plan to use, our motivations and expected results, and some preliminary limitations of our work.