# Preface

In April 2025, the Supreme Court of the United Kingdom ruled, in a deeply flawed decision, that the term "sex" in the 2010 Equality Act should be interpreted as perceived biological sex. This was a case brought by a transphobic hate group; supported by other transphobic hate groups; considered with explicit rejection of input from transgender or intersex people or from legitimate feminist groups; and ruled on by justices who presented no clear understanding of biology, relevant legal history, or human rights obligations [@Goodlaw-Supreme-Court].

The Labour government had the power and the moral obligation to reassert, through legislation, the legal rights and dignity of transgender people. They abrogated this responsibility [@Starmer-Transphobia].

This wasn't a decision made in isolation. The sociopolitical landscape of the UK has been driven into artificial culture wars, stripping the rights of women (most sharply of transgender women), of refugees, of children, and of myriad other minority groups. 

Take a single thread of this backsliding: the squatter's scene, for a long time the epicentre of queer and women's support networks [@Feminist-Squats], has been systematically dismantled [@Death-of-Squatting]. Women's and queer refuges, whose institutional legitimacy allowed them to survive and stem the bleeding for a while, have seen funding slashed [@Shelter-Funding; @Therapy-Funding] and beds overwhelmed [@National-Shelter-Shortage; @Bristol-Shelter-Shortage]. Women and queer folk forced into poverty by these systemic failures have often turned to irregular employment, including sex work; the systemic response has not been to address the roots of poverty, but to crack down on the ability of these folk to work safely and within the law [@Sex-Work-Criminalisation]. 

This one thread of marginalisation - predominantly affecting women, though not uniquely - is woven into a rich tapestry of cryptic discrimination: actions that strip the rights, dignity and safety of marginalised groups, hidden under thin guises of paternalistic concern, economic pseudo-objectivity, or legalistic frameworks. 

The same patterns are seen when children are stripped of their rights to privacy, healthcare, and even information access; when refugees are refused safe passage across the channel, the ability to work while their case is heard, or the dignity of defense by the government or media; when traveller communities are systemtically disrupted by local councils, or harassed by police and private enforcement agencies; and when the range of permissable womanhood is policed by a minority of white bigots, who are all too willing to strip it from athletes, politicians, and other figures who don't meet a narrow worldview.

It can be difficult to see how to unpick this discriminatory weave, especially at a time where right-wing actors in the UK are far better organised than our fragmentary and damaged progressive networks. Resistance takes organisation, and organisation takes a clear understanding of how and why our communities are fragmented. We must take responsibility for healing and community-building.

One fact must be made unambiguous: neither the Supreme Court, nor the government, nor any hate groups, can decide morality. The legal complications posed by the Supreme Court ruling, and the subsequent EHRC guidance, do not absolve us of our moral responsibility to ensure transgender people are allowed to live in dignity. We are required to find ways to ensure transgender people are not forced into the wrong bathrooms, or third-gendered, or degraded by our legal and social systems. We are required to ensure that transgender people are not forced into detransition, either by pseudomedical hate groups, by intentional beaurocracy of healthcare, or by the crushing weight of gendered poverty. If this conflicts with the law, we have a moral obligation to change that law, or to break it.

So, too, do we have an obligation to uphold the dignity of women. We must hold to account those who demean or demonise women. We must act preemptively and prevocatively to create a society that is safe, where misogynistic acts are unthinkable. We must refuse the policing of womanhood, dismiss the regressive notions that women can be defined by biology, appearance or social roles. We must dismantle gendered poverty, and while working to dismantle it, must refuse to demean the victims, must provide power to sex workers and homeless women and survivors of domestic abuse. Women must hold dignity, not by edict of a government who grants and revokes their rights at a whim, but by a comprehensive and unbreakable social power, by a society that enforces this dignity, whether with the support of structural power or in defiance of it.

Despite cynical, paternalistic and transphobic claims otherwise, these obligations are harmonious and intertwined. In rejecting bioessentialist narratives of womanhood, and rejecting the artificial and narrow acceptable womanhood constructed by transphobes, we deconstruct the roles and obligations assigned to women in a patriarchal system. In rejecting the power structures that enforce their narrow vision of womanhood, we construct a more expansive, permissive and free understanding of womanhood that allows for gender diversity to exist not just at the margins, but as a permeation of culture.

This project came about in this context, and in the context of my personal experiences with transphobia, male dominance and community structure in the world of petplay. It's goal is to support community-building and promote the needs of women and transgender people through a data-driven approach.

This project has been supported by far too many individuals, creatures and others to name, but some special thanks must be given to the draft horse Morningstar Tarax and the pup Cloudy who proof-read various documents; to the fox Shona and the doll collection Bee who helped me develop my thoughts for this writeup; to the pup Akro, who helped with analysing data; and to the innumerable people in the petplay scene with whom I've commiserated on the troubles caused by gender.